server:
  port: 8082
spring:
  application:
    name: "tensquare_recruit"  #指定服务名
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: "jdbc:mysql://192.168.124.61:3306/tensquare_recruit?useUnicode=true&characterEncoding=UTF-8&useSSL=false"
    username: "root"
    password: "ROOT"
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: "SELECT1FROMDUAL"
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      filter:
        stat:
          log-slow-sql: true
    commons-log:
    connection-logger-name: "stat,wall,log4j"
  aop:
    proxy-target-class: true

# 配置mybatis-plus
mybatis-plus:
  #配置扫描xml
  mapper-locations: "com/tensquare/recruit/mapper/*.xml"
  type-aliases-package: "com.tensquare.recruit"
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 2
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 2
    #驼峰下划线转换
    db-column-underline: true
    #刷新mapper 调试神器
    refresh-mapper: true
  #数据库大写下划线转换
  #capital-mode: true
  #序列接口实现类配置
  #key-generator: com.baomidou.springboot.xxx
  #逻辑删除配置（下面3个配置）
  #    logic-delete-value: 0
  #    logic-not-delete-value: 1
  #自定义SQL注入器
  #sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector
  #自定义填充策略接口实现
  #meta-object-handler: com.baomidou.springboot.xxx
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
